from tkinter import *
def click(event):
    global scvalue
    text = event.widget.cget("text")
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            try:
                value = eval(screen.get())
            except exception as e:
                print(e)
                value = "error"
        scvalue.set(value)
        screen.update()
    elif text == "c":
        scvalue.set("")
        screen.update()
    elif text == "x":
        
        scvalue.set(text[ len(screen.get()):0:-1])
        screen.update()

    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root = Tk()
root.geometry("855x733")
root.title("making the python calculator")

scvalue = StringVar()
scvalue.set("")
f = Frame(root,bg = "red")
screen = Entry(f,textvar = scvalue,font = "lucida 40 bold",bg = "grey")
screen.pack(fill = Y,ipadx = 2,padx = 2,pady = 8)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "9",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey",border = 2)
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "8",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "7",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "6",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "5",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "4",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "3",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "2",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "1",padx = 20,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "+",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=13.5,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "-",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=13.2,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "*",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=13.2,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "/",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=13.5,pady = 7)
b.bind("<Button-1>", click)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "%",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=8.5,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "=",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=8.5,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "/",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=8.5,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "x",padx = 12.1,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=8.5,pady = 7)
b.bind("<Button-1>", click)
f.pack()
f = Frame(root,bg  = "red")
b = Button(f,text = "c",padx = 18,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = ".",padx = 18,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
b = Button(f,text = "00",padx =18,pady = 8,font = "lucida 35 bold",bg = "grey")
b.pack(side = LEFT,padx=20,pady = 7)
b.bind("<Button-1>", click)
f.pack()
root.mainloop()